### ISSUE TITLE
Generating waveforms in a for loop

### ISSUE THREAD

**Issue by iforwms** [Idnan/SoundCloud-Waveform-Generator#1]
Hi,

I'm running `SoundCloudWaveform.generate` within a `for` loop; the problem is the image is being overwritten each iteration. I.e. the second waveform is written on top of the first waveform. Is it possible to reset the image data for each loop?

Here's my code:

```
for (var i = 0; i < files.length; i++) {
    var file = files[i];

    // Generate waveforms
    SoundCloudWaveform.generate(file, {

      onComplete: function(png, pixels) {
          var canvas = document.createElement('canvas');
          container.appendChild(canvas);
          canvas.setAttribute('class', 'waveform')
          var context = canvas.getContext('2d');
          context.putImageData(pixels, 0, 0);
      }
    });
  }
```

Thanks,

-ifor

**Comment by Idnan** [comment]
@iforwms bug is fixed. Please re-clone.
Thanks
